import AuthLayout from "@/components/AuthLayout";
import { AuthContext, AuthContextInterface } from "@/context/AuthContext";
import { NextPageWithLayout } from "@/pages/_app";
import { Button, Form, Input } from "antd";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import * as React from "react";

const Login: NextPageWithLayout = () => {
  //#region ::: Variable Initialisations
  const { login } = React.useContext(AuthContext) as AuthContextInterface;
  //#endregion ::: Variable Initialisations

  //#region ::: Handlers
  const handleForm = (values: any) => {
    login(values);
  };

  const handleFormFailed = (errorInfo: any) => {
    console.error("Failed:", errorInfo);
  };
  //#endregion ::: Handlers

  //#region ::: Other Methods

  //#endregion ::: Other Methods

  //#region ::: UseEffect
  //#endregion ::: UseEffect

  return (
    <>
      <Head>
        <title>Login | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="my-auto mx-auto max-w-[600px]">
          <div className="mx-auto mb-6 w-1/2 mix-blend-multiply md:w-2/5">
            <Link href={"/"}>
              <div>
                <Image
                  src={"/logo_kpid.png"}
                  width={626}
                  height={160}
                  alt="Logo KPID Jawa Timur"
                />
              </div>
            </Link>
          </div>
          <div className="rounded-lg bg-white shadow-custom">
            <div className="rounded-t-lg bg-sky-100 p-6 pb-4">
              <h2 className="text-center text-2xl font-semibold text-sky-700">
                Masuk ke Akun Anda
              </h2>
            </div>
            <div className="p-6 pt-4">
              <Form
                name="login_form"
                onFinish={handleForm}
                onFinishFailed={handleFormFailed}
                autoComplete="off"
                layout="vertical"
                className="custom-form"
                requiredMark={"optional"}
              >
                <Form.Item
                  label="Email"
                  name="email"
                  rules={[
                    { required: true, message: "Silakan masukkan email Anda" },
                    { type: "email", message: "Alamat email tidak valid!" },
                  ]}
                >
                  <Input />
                </Form.Item>

                <Form.Item
                  label="Password"
                  name="password"
                  rules={[
                    {
                      required: true,
                      message: "Silakan masukkan password Anda",
                    },
                  ]}
                >
                  <Input.Password />
                </Form.Item>

                <Form.Item>
                  <Button
                    className="mt-4 w-full py-2 text-lg md:text-xl"
                    type="primary"
                    htmlType="submit"
                  >
                    Login
                  </Button>
                </Form.Item>
              </Form>
            </div>
          </div>

          <div className="mt-8 rounded-lg bg-sky-100 p-4 text-center text-sm text-sky-700 shadow-custom md:text-base">
            Belum memiliki akun?
            <Link href={"/auth/register"}>
              <a className="font-semibold text-sky-700 hover:text-sky-500">
                {" "}
                Daftar
              </a>
            </Link>
          </div>
        </div>
      </>
    </>
  );
};

export default Login;

Login.getLayout = function getLayout(page: React.ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};
