import {
  faArrowTrendUp,
  faEquals,
  faNotEqual,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import { ReactElement, useContext } from "react";
import ChartCard from "../components/ChartCard";
import Layout from "../components/Layout";
import { AuthContext, AuthContextInterface } from "../context/AuthContext";
import { chart1 } from "./statistic";
import { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  const { userData } = useContext(AuthContext) as AuthContextInterface;

  return (
    <>
      <Head>
        <title>Moderasi Video | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-1 flex-col gap-4">
        <section className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="hidden rounded-md bg-white p-6 shadow-custom md:block">
            <h2 className="text-2xl font-semibold capitalize">
              Hai {userData.name}!
            </h2>
            <p className="mb-4 text-lg">
              Selamat Datang di Sistem Rekomendasi KPID Jawa Timur!
            </p>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Blanditiis consectetur voluptatum nostrum facere quae commodi,
              culpa recusandae illum ut dolorem.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="gap-4 rounded-md bg-white p-6 shadow-custom">
              <div className="flex">
                <div className="flex-1">
                  <h3 className="">Video Terunggah</h3>
                  <p className="text-2xl font-bold">2048</p>
                </div>
                <div className="my-auto flex h-12 w-12 items-center justify-center rounded-xl bg-green-100">
                  <FontAwesomeIcon
                    icon={faEquals}
                    height="24px"
                    className="text-2xl text-green-500"
                  />
                </div>
              </div>
              <div className="mt-4 flex gap-2 rounded-lg bg-slate-100 p-3.5">
                <span className="flex gap-2 text-green-500">
                  <FontAwesomeIcon icon={faArrowTrendUp} height="24px" /> 25.25%
                </span>{" "}
                dari bulan lalu.
              </div>
            </div>
            <div className="gap-4 rounded-md bg-white p-6 shadow-custom">
              <div className="flex">
                <div className="flex-1">
                  <h3 className="">Video Terdeteksi Melanggar</h3>
                  <p className="text-2xl font-bold">1024</p>
                </div>
                <div className="my-auto flex h-12 w-12 items-center justify-center rounded-xl bg-red-100">
                  <FontAwesomeIcon
                    icon={faNotEqual}
                    height="24px"
                    className="text-2xl text-red-500"
                  />
                </div>
              </div>
              <div className="mt-4 flex gap-2 rounded-lg bg-slate-100 p-3.5">
                <span className="flex gap-2 text-red-500">
                  <FontAwesomeIcon icon={faArrowTrendUp} height="24px" /> 25.25%
                </span>{" "}
                dari bulan lalu.
              </div>
            </div>
          </div>
        </section>
        <section className="flex min-h-[20rem] flex-1 grow flex-col rounded-lg bg-white">
          <ChartCard chartData={chart1} title={chart1.title}></ChartCard>
        </section>
      </div>
    </>
  );
};

export default Home;

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
