import { Button, Form, Input, Tabs } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { ReactNode, useContext } from "react";
import Navbar from "../components/Navbar";
import { AuthContext, AuthContextInterface } from "../context/AuthContext";

const Home: NextPage = () => {
  let router = useRouter();
  let { tab } = router.query;
  const { login } = useContext(AuthContext) as AuthContextInterface;

  const onFinish = (values: any) => {
    login(values);
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };

  const loginForm: ReactNode = (
    <Form
      name="login_form"
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
      autoComplete="off"
      layout="vertical"
    >
      <Form.Item
        label="Email"
        name="email"
        rules={[{ required: true, message: "Please input your email!" }]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Password"
        name="password"
        rules={[
          {
            required: true,
            message: "Please input your password!",
          },
        ]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item>
        <Button
          className="mt-4 py-2 text-xl w-full"
          type="primary"
          htmlType="submit"
        >
          Login
        </Button>
      </Form.Item>
    </Form>
  );
  const registerForm: ReactNode = (
    <Form
      name="register_form"
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
      autoComplete="off"
      layout="vertical"
    >
      <Form.Item
        label="Nama"
        name="name"
        rules={[{ required: true, message: "Please input your name!" }]}
      >
        <Input />
      </Form.Item>
      <Form.Item
        label="Email"
        name="email"
        rules={[{ required: true, message: "Please input your email!" }]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Password"
        name="password"
        rules={[{ required: true, message: "Please input your password!" }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item>
        <Button
          className="mt-4 py-2 text-xl w-full"
          type="primary"
          htmlType="submit"
        >
          Register
        </Button>
      </Form.Item>
    </Form>
  );

  return (
    <div>
      <Head>
        <title>Login | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <section className="flex-1 flex flex-col justify-center items-center min-h-screen bg-gradient-to-t from-sky-700 to-sky-400">
          <Link href="/">
            <a>
              <Image
                src={"/logo_kpid.png"}
                width={626}
                height={160}
                alt="Logo KPID Jawa Timur"
              />
            </a>
          </Link>
          {/* <Image
            src={"/login_defend.png"}
            width={423}
            height={423}
            alt="KPID Melindungi"
          /> */}
          <p className="text-justify text-lg uppercase font-light opacity-80 tracking-tight mt-16 md:w-3/4 text-white">
            Website Moderasi Video KPID Jawa Timur 2023
          </p>
          <p className="text-justify text-2xl mt-4 md:w-3/4 text-white">
            Melindungi masyarakat Indonesia dari konten mengandung 5S: SARU,
            SARA, SADIS, SIHIR, dan Siaran Partisan & Ilegal melalui pengawasan
            siaran televisi
          </p>
        </section>
        <section className="flex-1 flex flex-col min-h-screen">
          <div className="my-auto mx-16">
            <div>
              <Tabs
                className="custom-tabs"
                type="card"
                defaultActiveKey={tab == "register" ? "2" : "1"}
                items={[
                  {
                    label: `Login`,
                    key: `1`,
                    children: loginForm,
                  },
                  {
                    label: `Register`,
                    key: `2`,
                    children: registerForm,
                  },
                ]}
              />
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default Home;
