import { Button, Form, Input } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import Navbar from "../components/Navbar";
import { AuthContext, AuthContextInterface } from "../context/AuthContext";

const Home: NextPage = () => {
  let router = useRouter();
  const { login } = useContext(AuthContext) as AuthContextInterface;

  const onFinish = (values: any) => {
    login(values);
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };

  return (
    <div>
      <Head>
        <title>Login | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <div className="my-auto mx-4 sm:m-auto">
            <div className="sm:bg-gray-50 p-8 rounded-md sm:shadow-lg">
              <h1 className="text-lg">Login</h1>
              <Form
                name="login_form"
                onFinish={onFinish}
                onFinishFailed={onFinishFailed}
                autoComplete="off"
                layout="vertical"
              >
                <Form.Item
                  label="Email"
                  name="email"
                  rules={[
                    { required: true, message: "Please input your email!" },
                  ]}
                >
                  <Input />
                </Form.Item>

                <Form.Item
                  label="Password"
                  name="password"
                  rules={[
                    { required: true, message: "Please input your password!" },
                  ]}
                >
                  <Input.Password />
                </Form.Item>

                <Form.Item>
                  <Button type="primary" htmlType="submit">
                    Login
                  </Button>
                </Form.Item>
              </Form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
