import AuthLayout from "@/components/AuthLayout";
import Sadis from "@/components/icons/Sadis";
import Sara from "@/components/icons/Sara";
import Saru from "@/components/icons/Saru";
import SiaranPartisan from "@/components/icons/SiaranPartisan";
import Sihir from "@/components/icons/Sihir";
import { AuthContext, AuthContextInterface } from "@/context/AuthContext";
import { Button, Divider, Form, Input, message } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import * as React from "react";
import { NextPageWithLayout } from "./_app";

const Register: NextPageWithLayout = () => {
  let router = useRouter();
  const { isLoggedIn, register } = React.useContext(
    AuthContext
  ) as AuthContextInterface;

  React.useEffect(() => {
    if (isLoggedIn) {
      message.loading("Redirecting...");
      router.push("/");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoggedIn]);

  const onFinish = (values: any) => {
    register(values);
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };

  return (
    <>
      <Head>
        <title>Register | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex min-h-screen flex-col bg-slate-100 px-8 md:px-16">
        <div className="my-auto mx-auto max-w-[600px]">
          <div className="mx-auto mb-6 w-1/2 mix-blend-multiply md:w-2/5">
            <Link href={"/"}>
              <Image
                src={"/logo_kpid.png"}
                width={626}
                height={160}
                alt="Logo KPID Jawa Timur"
              />
            </Link>
          </div>
          <div className="rounded-lg bg-white p-6 pb-8 shadow-custom">
            <h2 className="text-center text-lg font-semibold md:text-xl">
              Daftarkan Akun Anda
            </h2>
            <Divider className="my-4" />
            <Form
              name="register_form"
              onFinish={onFinish}
              onFinishFailed={onFinishFailed}
              autoComplete="off"
              layout="vertical"
              requiredMark={"optional"}
            >
              <Form.Item
                label="Nama"
                name="name"
                rules={[{ required: true, message: "Please input your name!" }]}
              >
                <Input />
              </Form.Item>
              <Form.Item
                label="Email"
                name="email"
                rules={[
                  { required: true, message: "Please input your email!" },
                ]}
              >
                <Input />
              </Form.Item>

              <Form.Item
                label="Password"
                name="password"
                rules={[
                  { required: true, message: "Please input your password!" },
                ]}
              >
                <Input.Password />
              </Form.Item>

              <Form.Item>
                <Button
                  className="mt-4 w-full py-2 text-lg md:text-xl"
                  type="primary"
                  htmlType="submit"
                >
                  Register
                </Button>
              </Form.Item>
            </Form>
          </div>

          <div className="mt-8 rounded-lg bg-slate-200 p-4 text-center text-sm shadow-custom md:text-base">
            Sudah memiliki akun?
            <Link href={"/login"}>
              <a className="text-blue-500"> Masuk</a>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
};

const IconWrapperClass = "h-full flex flex-col items-center my-2";
const IconCardClass = "rounded-lg p-2 bg-slate-900 bg-opacity-30 shadow-custom";
const IconSubtitleClass = "mt-2 text-lg text-center";

export default Register;

Register.getLayout = function getLayout(page: React.ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};
