import Layout from "@/components/Layout";
import debounce from "@/utils/Debounce";
import { AutoComplete, Button, Form, Select } from "antd";
import Head from "next/head";
import * as React from "react";
import { NextPageWithLayout } from "./_app";

export const chart1 = {
  title: "Statistik Moderasi Sebulan Terakhir",
  key1: "Total Video",
  key2: "Video Melanggar",
  data: [
    { name: "1-3-2023", "Total Video": 68, "Video Melanggar": 37 },
    { name: "2-3-2023", "Total Video": 90, "Video Melanggar": 7 },
    { name: "3-3-2023", "Total Video": 84, "Video Melanggar": 47 },
    { name: "4-3-2023", "Total Video": 12, "Video Melanggar": 5 },
    { name: "5-3-2023", "Total Video": 28, "Video Melanggar": 1 },
    { name: "6-3-2023", "Total Video": 47, "Video Melanggar": 43 },
    { name: "7-3-2023", "Total Video": 59, "Video Melanggar": 15 },
    { name: "8-3-2023", "Total Video": 68, "Video Melanggar": 7 },
    { name: "9-3-2023", "Total Video": 88, "Video Melanggar": 26 },
    { name: "10-3-2023", "Total Video": 44, "Video Melanggar": 10 },
    { name: "11-3-2023", "Total Video": 30, "Video Melanggar": 16 },
    { name: "12-3-2023", "Total Video": 49, "Video Melanggar": 7 },
    { name: "13-3-2023", "Total Video": 96, "Video Melanggar": 15 },
    { name: "14-3-2023", "Total Video": 11, "Video Melanggar": 5 },
    { name: "15-3-2023", "Total Video": 96, "Video Melanggar": 6 },
    { name: "16-3-2023", "Total Video": 82, "Video Melanggar": 9 },
    { name: "17-3-2023", "Total Video": 89, "Video Melanggar": 33 },
    { name: "18-3-2023", "Total Video": 43, "Video Melanggar": 3 },
    { name: "19-3-2023", "Total Video": 87, "Video Melanggar": 53 },
    { name: "20-3-2023", "Total Video": 31, "Video Melanggar": 14 },
    { name: "21-3-2023", "Total Video": 76, "Video Melanggar": 67 },
    { name: "22-3-2023", "Total Video": 95, "Video Melanggar": 16 },
    { name: "23-3-2023", "Total Video": 27, "Video Melanggar": 8 },
    { name: "24-3-2023", "Total Video": 93, "Video Melanggar": 43 },
    { name: "25-3-2023", "Total Video": 9, "Video Melanggar": 6 },
    { name: "26-3-2023", "Total Video": 13, "Video Melanggar": 7 },
    { name: "27-3-2023", "Total Video": 84, "Video Melanggar": 21 },
    { name: "28-3-2023", "Total Video": 8, "Video Melanggar": 6 },
    { name: "29-3-2023", "Total Video": 18, "Video Melanggar": 2 },
    { name: "30-3-2023", "Total Video": 38, "Video Melanggar": 15 },
  ],
};

const Statistic: NextPageWithLayout = () => {
  const [selectOptions, setSelectOptions] = React.useState([
    {
      value: "jack",
      label: "Jack",
    },
    {
      value: "lucy",
      label: "Lucy",
    },
    {
      value: "tom",
      label: "Tom",
    },
  ]);

  const [modifiedSelectOptions, setModifiedSelectOptions] =
    React.useState<any[]>();
  const getStatusStyling = (status: string) => {
    switch (status.toLowerCase()) {
      case "initialized":
        return {
          className: "bg-slate-300",
          text: "Sedang Diunggah",
        };
      case "uploaded":
        return {
          className: "bg-amber-400",
          text: "Belum Diproses",
        };
      case "in_progress":
        return {
          className: "bg-blue-500",
          text: "Sedang Diproses",
        };
      case "approved":
        return {
          className: "bg-green-500",
          text: "Tidak Ditemukan Pelanggaran",
        };
      case "rejected":
        return {
          className: "bg-red-600 text-white",
          text: "Ditemukan Pelanggaran",
        };
      default:
        return {
          className: "bg-stone-700 text-white",
          text: "Status Tidak Diketahui",
        };
    }
  };

  const statuses: string[] = [
    "initialized",
    "uploaded",
    "in_progress",
    "approved",
    "rejected",
    "t",
  ];

  React.useEffect(() => {
    setModifiedSelectOptions(
      selectOptions.map((option) => {
        return {
          ...option,
        };
      })
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onChange = (value: string) => {
    console.log(`selected ${value}`);
  };

  const onSearch = debounce((value: string) => {
    setModifiedSelectOptions(
      selectOptions.filter((option) =>
        option.label.toLowerCase().includes(value.toLowerCase())
      )
    );
  }, 250);

  const onFinish = (values: any) => {
    selectOptions.push({
      value: values.testing.toLowerCase(),
      label: values.testing,
    });
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };

  return (
    <div>
      <Head>
        <title>Statistik Moderasi | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <Form
          name="basic"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          initialValues={{ remember: true }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
        >
          <Form.Item label="Testing" name="testing">
            <AutoComplete
              className="min-w-[16ch]"
              onSearch={onSearch}
              placeholder="Select a person"
              options={modifiedSelectOptions}
            />
          </Form.Item>

          <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>

        <div className="mb-8"></div>
        {statuses.map((status, index) => {
          return (
            <div
              key={index}
              className={
                " rounded-tr-lg rounded-bl-lg py-2 px-4  text-sm font-semibold tracking-wide " +
                getStatusStyling(status).className
              }
            >
              {getStatusStyling(status).text}
            </div>
          );
        })}
        {/* <Navbar />
        <div className="flex flex-wrap">
          <ChartCard chartData={chart1} title={chart1.title}></ChartCard>
          <ChartCard chartData={chart2} title={chart2.title}></ChartCard>
        </div> */}
      </div>
    </div>
  );
};

export default Statistic;

Statistic.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};
