import ChartCard from "@/components/ChartCard";
import Navbar from "@/components/Navbar";
import type { NextPage } from "next";
import Head from "next/head";

export const chart1 = {
  title: "Statistik Moderasi Sebulan Terakhir",
  key1: "Total Video",
  key2: "Video Melanggar",
  data: [
    { name: "1-3-2023", "Total Video": 68, "Video Melanggar": 37 },
    { name: "2-3-2023", "Total Video": 90, "Video Melanggar": 7 },
    { name: "3-3-2023", "Total Video": 84, "Video Melanggar": 47 },
    { name: "4-3-2023", "Total Video": 12, "Video Melanggar": 5 },
    { name: "5-3-2023", "Total Video": 28, "Video Melanggar": 1 },
    { name: "6-3-2023", "Total Video": 47, "Video Melanggar": 43 },
    { name: "7-3-2023", "Total Video": 59, "Video Melanggar": 15 },
    { name: "8-3-2023", "Total Video": 68, "Video Melanggar": 7 },
    { name: "9-3-2023", "Total Video": 88, "Video Melanggar": 26 },
    { name: "10-3-2023", "Total Video": 44, "Video Melanggar": 10 },
    { name: "11-3-2023", "Total Video": 30, "Video Melanggar": 16 },
    { name: "12-3-2023", "Total Video": 49, "Video Melanggar": 7 },
    { name: "13-3-2023", "Total Video": 96, "Video Melanggar": 15 },
    { name: "14-3-2023", "Total Video": 11, "Video Melanggar": 5 },
    { name: "15-3-2023", "Total Video": 96, "Video Melanggar": 6 },
    { name: "16-3-2023", "Total Video": 82, "Video Melanggar": 9 },
    { name: "17-3-2023", "Total Video": 89, "Video Melanggar": 33 },
    { name: "18-3-2023", "Total Video": 43, "Video Melanggar": 3 },
    { name: "19-3-2023", "Total Video": 87, "Video Melanggar": 53 },
    { name: "20-3-2023", "Total Video": 31, "Video Melanggar": 14 },
    { name: "21-3-2023", "Total Video": 76, "Video Melanggar": 67 },
    { name: "22-3-2023", "Total Video": 95, "Video Melanggar": 16 },
    { name: "23-3-2023", "Total Video": 27, "Video Melanggar": 8 },
    { name: "24-3-2023", "Total Video": 93, "Video Melanggar": 43 },
    { name: "25-3-2023", "Total Video": 9, "Video Melanggar": 6 },
    { name: "26-3-2023", "Total Video": 13, "Video Melanggar": 7 },
    { name: "27-3-2023", "Total Video": 84, "Video Melanggar": 21 },
    { name: "28-3-2023", "Total Video": 8, "Video Melanggar": 6 },
    { name: "29-3-2023", "Total Video": 18, "Video Melanggar": 2 },
    { name: "30-3-2023", "Total Video": 38, "Video Melanggar": 15 },
  ],
};
const chart2 = {
  title: "Statistik Pengguna Unik",
  key1: "Total Pengguna",
  data: [
    { name: 1, "Total Pengguna": 37 },
    { name: 2, "Total Pengguna": 7 },
    { name: 3, "Total Pengguna": 47 },
    { name: 4, "Total Pengguna": 5 },
    { name: 5, "Total Pengguna": 1 },
    { name: 6, "Total Pengguna": 43 },
    { name: 7, "Total Pengguna": 15 },
    { name: 8, "Total Pengguna": 7 },
    { name: 9, "Total Pengguna": 26 },
    { name: 10, "Total Pengguna": 10 },
    { name: 11, "Total Pengguna": 16 },
    { name: 12, "Total Pengguna": 7 },
    { name: 13, "Total Pengguna": 15 },
    { name: 14, "Total Pengguna": 5 },
    { name: 15, "Total Pengguna": 6 },
    { name: 16, "Total Pengguna": 9 },
    { name: 17, "Total Pengguna": 33 },
    { name: 18, "Total Pengguna": 3 },
    { name: 19, "Total Pengguna": 53 },
    { name: 20, "Total Pengguna": 14 },
    { name: 21, "Total Pengguna": 67 },
    { name: 22, "Total Pengguna": 16 },
    { name: 23, "Total Pengguna": 8 },
    { name: 24, "Total Pengguna": 43 },
    { name: 25, "Total Pengguna": 6 },
    { name: 26, "Total Pengguna": 7 },
    { name: 27, "Total Pengguna": 21 },
    { name: 28, "Total Pengguna": 6 },
    { name: 29, "Total Pengguna": 2 },
    { name: 30, "Total Pengguna": 15 },
  ],
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Statistik Moderasi | KPID Jawa Timur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <Navbar />
        <div className="flex flex-wrap">
          <ChartCard chartData={chart1} title={chart1.title}></ChartCard>
          <ChartCard chartData={chart2} title={chart2.title}></ChartCard>
        </div>
      </div>
    </div>
  );
};

export default Home;
